### ISSUE TITLE
Help - Emulator stop running

### ISSUE THREAD

**Issue by loremont** [GoogleCloudPlatform/cloud-spanner-emulator#10]
I'm trying emulator version 1.1.1 but I have a problem with foreign key.

I start emulator on my local windows system with command
`gcloud beta emulators spanner start`
and I can see Emulator running on Docker.

After that I create a instance, a database and 2 tables:
`gcloud spanner instances create test-instance --config=emulator-config --description="Test Instance" --nodes=1`
`gcloud spanner databases create test-database --instance test-instance`
`gcloud spanner databases ddl update test-database --instance=test-instance --ddl="CREATE TABLE table1 (name1 STRING(64) NOT NULL, value1 INT64 NOT NULL) PRIMARY KEY(name1)"`
`gcloud spanner databases ddl update test-database --instance=test-instance --ddl="CREATE TABLE table2 (name2 STRING(64) NOT NULL, value2 INT64 NOT NULL, other_name STRING(64) NOT NULL) PRIMARY KEY(name2)"`

Up to here everything is ok and if I would see created tables on catalog I can execute:
`gcloud spanner databases execute-sql test-database --instance=test-instance --sql "select * from information_schema.tables"`

to obtain
![image](https://user-images.githubusercontent.com/74240907/98664140-43fae400-234a-11eb-977f-65e745ba97e7.png)

Now I add a foreign key constraint between table1 and table2:
`gcloud spanner databases ddl update test-database --instance=test-instance --ddl="ALTER TABLE table2 ADD FOREIGN KEY (other_name) REFERENCES table1(name1)"`

Command is executed and constraint is added, but now if I try to select information_schema again:
`gcloud spanner databases execute-sql test-database --instance=test-instance --sql "select * from information_schema.tables"`

emulator container on docker stop running unexpectedly

![image](https://user-images.githubusercontent.com/74240907/98664797-1c584b80-234b-11eb-98c3-24807bdc856a.png)

I can't understand. Could you help me?

**Comment by alapkarapurkar** [comment]
Thanks for the detailed bug report! We have a reproduction for this bug and a fix is in the works.

**Comment by alapkarapurkar** [comment]
Thanks again for the detailed report. The fix will be included in the next release (1.1.2).

This issue is triggered by information schema queries when a foreign key references the primary key of the referenced table. If it helps, you can also use gcloud ddl describe https://cloud.google.com/sdk/gcloud/reference/spanner/databases/ddl/describe to view the schema.

**Comment by jacobdufault-google** [comment]
Fixed by b0c06e0e17cac56af7d3335c18dfb1a780ff89d4
