### ISSUE TITLE
Mutation count feature

### ISSUE THREAD

**Issue by michity15169** [GoogleCloudPlatform/cloud-spanner-emulator#100]
Cloud Spanner has a limit of 40,000 Mutations per transaction[1]. I would like the Cloud Spanner Emulator to implement a function that will cause the transaction to fail if this limit is violated.

Also, it would be nice if the user could get the number of mutations I used even when executing transactions below the upper limit, as it would need to count mutations in order to implement this feature.

[1] https://cloud.google.com/spanner/quotas#limits-for

**Comment by gauravpurohit06** [comment]
Thanks @michity15169  for filing the request. We are tracking the enhancement with the internal development team and will get back.

**Comment by gauravpurohit06** [comment]
We did our investigation and the calculation for mutation count is not deterministic. Closing it.
