### ISSUE TITLE
Usable as an external WORKSPACE

### ISSUE THREAD

**Issue by philstahlfeld** [GoogleCloudPlatform/cloud-spanner-emulator#112]
**Note that I already have this working and am checking to see if y'all would like for me to contribute it back**

The Xoogler in me likes to have hermetic testing environments such that `bazel test //...` will run consistently across any environments where `bazel` is available and the source code is present. As such, I want all of my tests that are backed by Cloud Spanner to use a binary produced by `bazel` instead of having them depend on a binary installed somewhere on the system. 

This can be accomplished by including the `com_google_cloud_spanner_emulator` `WORKSPACE` as an external `WORKSPACE` in my project. Ideally, once all the dependencies are sorted out, running:
```
bazel run @com_google_cloud_spanner_emulator//binaries:gateway_main
```
should launch the emulator. However, I found some build issues that are only present when using the emulator as an external `WORKSPACE`. 

The three issues that I found and addressed are as follows:

1. The binary to populate the info schema columns metadata uses [hardcoded paths](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/16bdf843ac8ddabd06394c868d3b980d970a1bbc/backend/query/populate_info_schema_columns_metadata.cc#L51) to the metadata CSV files. I was able to address this issue by accessing the file paths via Runfiles.
2. The [rule to generate the DLLParser](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/16bdf843ac8ddabd06394c868d3b980d970a1bbc/backend/schema/parser/BUILD#L99) creates several `.cc` files that reference their headers via paths like: `#include "bazel-out/k8-fastbuild/bin/external/com_google_cloud_spanner_emulator/backend/schema/parser/DDLParserTokenManager.h"`, but the generated `cc_libary` doesn't include the root build directory as a path to find headers. To address this issue, I added `-iquote .` to the `copts` list in the [generated cc_library rule](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/16bdf843ac8ddabd06394c868d3b980d970a1bbc/backend/common/javacc_parser.bzl#L114).
3. For some reason (that I still don't understand), [this patch](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/master/build/bazel/golang_protobuf.patch) doesn't get applied and doesn't cause an error. To address this issue, I added the following snippet to the [gateway_main](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/16bdf843ac8ddabd06394c868d3b980d970a1bbc/binaries/BUILD#L36) target, which has the benefit of only disabling the proto registration conflict errors for this specific binary (instead of for my whole project).
```
env = {
    "GOLANG_PROTOBUF_REGISTRATION_CONFLICT": "ignore",
},
```

As I mentioned above, I already have fixes for all of these issues and I'm currently applying them as a patch when I add `com_google_cloud_spanner_emulator` to my `WORKSPACE`. If you would like, I can send the changes as a PR to contribute them back to this repo. You can preview the changes [here](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/compare/master...philstahlfeld:cloud-spanner-emulator:philstahlfeld-feat/ext-dep?expand=1).

**Comment by gauravpurohit06** [comment]
Thank you @philstahlfeld for flagging out the issue. Please feel free to raise the PR and we will merge it internally. It would be really helpful if you raise different PR for different issues you mentioned. 

Thank you very much!!
