### ISSUE TITLE
Add support for IF [NOT] EXISTS clause

### ISSUE THREAD

**Issue by taka-oyama** [GoogleCloudPlatform/cloud-spanner-emulator#119]
Official spanner seems to have added support for it and we'd like to use it.

https://cloud.google.com/spanner/docs/release-notes#June_09_2023

**Comment by gauravpurohit06** [comment]
Thank you @taka-oyama for logging the issue. We are working on it and it would be part of next release.

**Comment by taka-oyama** [comment]
I confirmed that this was working in `v1.5.7`. Thank you.
