### ISSUE TITLE
Performance of emulator

### ISSUE THREAD

**Issue by maroux** [GoogleCloudPlatform/cloud-spanner-emulator#12]
Hi

I upgraded from version 0.8.0 to version 1.1.0 and it seems like performance basically tanked. Rough numbers show about ~10x slower simple operations like database creation / deletes / insert an object (~10ms to ~100ms). There's no thread contention here, and I can get more concrete numbers using a demo app. I'm not sure if this is expected but this makes it much harder to use the emulator for testing and might need to go back to mocking :(

**Comment by Vizerai** [comment]
Hi, 
Thanks for bringing this to our attention. Can you provide some specific examples of cases that are now running slower?

**Comment by maroux** [comment]
Hi

Here's the gist to reproduce the problem: https://gist.github.com/maroux/089017562a975be0c9d5d4b4089b10f8

It looks like some kind of memory leak since the performance degrades with additional queries. 

The setup is pretty simple:
- A pytest fixture that creates a test instance (created once per test session).
- Another pytest fixture that creates a test database (created once per test, dropped at the end of test).
- Test creates tables and inserts rows. These insertions / queries get subsequently slower with more tests (represented in the gist by parametrized tests).

It looks like if I remove `snapshot.read`, then the problem goes away - of course this doesn't help for testing because we do expect to be able to read data back.

**Comment by Vizerai** [comment]
We recently pushed a new version of the emulator which is included in glcoud version 328. Can you verify if this is still an issue?
