### ISSUE TITLE
Add support for disable_query_null_filtered_index_check as a flag in gateway

### ISSUE THREAD

**Issue by progvb** [GoogleCloudPlatform/cloud-spanner-emulator#120]
Emulator release [v1.5.3](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.3) added support for the `disable_query_null_filtered_index_check` as a flag.

However, this flag isn't supported in gateway.

I can run emulator with `disable_query_null_filtered_index_check` directly, but I also need support for REST API, since I want to use gcloud CLI as well.

**Comment by gauravpurohit06** [comment]
Thank you @progvb for raising the PR. We have added it in the emulator and released the changes in the latest release. Thank you very much.
