### ISSUE TITLE
Allow max number of databases to be overriden at runtime. 

### ISSUE THREAD

**Issue by zweihan** [GoogleCloudPlatform/cloud-spanner-emulator#136]
We are using Spanner Emulator for testing. Each test would create its own database and teardown after. Due to concurrency, we sometimes hit the database limit of 100. While we understand that actual Spanner itself also has this limit, but we were wondering if it's possible to have a way to override this limit at run time?

**Comment by skuruppu** [comment]
Thanks for the question @zweihan. I will look into why this limitation exists and report back on whether it's possible to override the maximum at runtime.

Out of curiousity, how far above 100 do you think you might reach? Asking just in case it's not possible to set it dynamically.

**Comment by zweihan** [comment]
We are using it for testing, so the number is not realistic relative to actual spanner. Something in the thousands or tens of thousands would help.

**Comment by skuruppu** [comment]
So sorry for not updating this issue earlier. In [v1.2.24](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.24) we added support for this.

- `--override_max_databases_per_instance` flag was added to the emulator binary.
- If you're running the Docker image, to overide the flag, you have to set the `MAX_DATABASES_PER_INSTANCE` environment variable to configure this.

Note that the value will only be overriden if you set it to a value > 100.

**Comment by zweihan** [comment]
Thanks!
