### ISSUE TITLE
Emulator get stuck when the single transaction is not commited or rolled back

### ISSUE THREAD

**Issue by pedrohml** [GoogleCloudPlatform/cloud-spanner-emulator#137]
When using emulator, if the current/single transaction is not finalized (committed/rolled back) then all following operations are aborted and emulator throws an error saying `The emulator only supports one transaction at a time.`

Reproducibility:
1. Running emulator on docker: docker run -p 9010:9010 -p 9020:9020 gcr.io/cloud-spanner-emulator/emulator:latest
2. Start a transaction
3. Force the application to finish (not gracefully)

Suggestion:
> Add support to safely rollback any ongoing transaction(s). So the application can always execute it when starts

**Comment by olavloite** [comment]
We would prefer not adding any custom APIs to the emulator that are not present in Cloud Spanner.

You can however achieve what you want using the following trick:
1. The emulator does not allow you to start more than one read/write transaction per database.
2. Starting a new read/write transaction on a different session on the same database will fail for the above reason.
3. Starting a new read/write transaction on the same session that already has a read/write transaction will however succeed, as this automatically aborts the running transaction.
4. You can then rollback the transaction that was started in step 3 to get a 'transaction-free' database on the emulator.

That means that a small utility that does the following will reset the emulator for you:
1. Loop through all the databases on the emulator.
2. Loop through all the sessions on that database.
3. Start a new read/write transaction on each session, and then rollback that transaction.

The following class implements a couple of utility methods that you can use to reset the emulator before running your tests (Note: This example is in Java. Please give me a ping if you use a different programming language and are not able to convert it to that language):

```java
package com.google.cloud.spanner;

import com.google.api.gax.core.NoCredentialsProvider;
import com.google.api.gax.grpc.InstantiatingGrpcChannelProvider;
import com.google.cloud.spanner.admin.database.v1.DatabaseAdminClient;
import com.google.cloud.spanner.admin.database.v1.DatabaseAdminSettings;
import com.google.cloud.spanner.admin.instance.v1.InstanceAdminClient;
import com.google.cloud.spanner.admin.instance.v1.InstanceAdminSettings;
import com.google.cloud.spanner.v1.SpannerClient;
import com.google.cloud.spanner.v1.SpannerSettings;
import com.google.spanner.admin.database.v1.Database;
import com.google.spanner.admin.instance.v1.Instance;
import com.google.spanner.v1.BeginTransactionRequest;
import com.google.spanner.v1.RollbackRequest;
import com.google.spanner.v1.Session;
import com.google.spanner.v1.Transaction;
import com.google.spanner.v1.TransactionOptions;
import com.google.spanner.v1.TransactionOptions.ReadWrite;
import io.grpc.ManagedChannelBuilder;

public class EmulatorUtil {

  /** Removes all read/write transactions for all databases on the emulator for the given project. */
  public static void resetAllEmulatorTransactions(String project) throws Exception {
    try (InstanceAdminClient instanceAdminClient =
            InstanceAdminClient.create(
                InstanceAdminSettings.newBuilder()
                    .setCredentialsProvider(NoCredentialsProvider.create())
                    .setTransportChannelProvider(
                        InstantiatingGrpcChannelProvider.newBuilder()
                            .setEndpoint("localhost:9010")
                            .setChannelConfigurator(ManagedChannelBuilder::usePlaintext)
                            .build())
                    .build());
        DatabaseAdminClient databaseAdminClient =
            DatabaseAdminClient.create(
                DatabaseAdminSettings.newBuilder()
                    .setCredentialsProvider(NoCredentialsProvider.create())
                    .setTransportChannelProvider(
                        InstantiatingGrpcChannelProvider.newBuilder()
                            .setEndpoint("localhost:9010")
                            .setChannelConfigurator(ManagedChannelBuilder::usePlaintext)
                            .build())
                    .build())) {
      for (Instance instance :
          instanceAdminClient.listInstances(String.format("projects/%s", project)).iterateAll()) {
        for (Database database :
            databaseAdminClient.listDatabases(instance.getName()).iterateAll()) {
          resetEmulatorTransactions(database);
        }
      }
    }
  }

  /** Removes all read/write transactions for the given database on the emulator. */
  public static void resetEmulatorTransactions(Database database) throws Exception {
    try (SpannerClient spannerClient =
        SpannerClient.create(
            SpannerSettings.newBuilder()
                .setCredentialsProvider(NoCredentialsProvider.create())
                .setTransportChannelProvider(
                    InstantiatingGrpcChannelProvider.newBuilder()
                        .setEndpoint("localhost:9010")
                        .setChannelConfigurator(ManagedChannelBuilder::usePlaintext)
                        .build())
                .build())) {
      for (Session session : spannerClient.listSessions(database.getName()).iterateAll()) {
        Transaction transaction =
            spannerClient.beginTransaction(
                BeginTransactionRequest.newBuilder()
                    .setSession(session.getName())
                    .setOptions(
                        TransactionOptions.newBuilder()
                            .setReadWrite(ReadWrite.newBuilder().build())
                            .build())
                    .build());
        spannerClient.rollback(
            RollbackRequest.newBuilder()
                .setSession(session.getName())
                .setTransactionId(transaction.getId())
                .build());
      }
    }
  }
}
```

**Comment by olavloite** [comment]
@pedrohml Does the above-mentioned workaround solve your problem?

**Comment by olavloite** [comment]
Closing this issue as a workaround has been provided. Please feel free to reopen if this does not solve the problem for you.

**Comment by pedrohml** [comment]
Thanks for the response. I am currently using python sdk. Will try to adapt the workaround there.

**Comment by olavloite** [comment]
> Thanks for the response. I am currently using python sdk. Will try to adapt the workaround there.

OK, let me know if you run into any problems with that.

**Comment by wray27** [comment]
@pedrohml any success in producing a workaround in python?

**Comment by csibe17** [comment]
Based on @olavloite recommendation, I am sharing my working python implementation if it helps for anyone.

```python
from google.cloud import spanner, spanner_v1

def cleanup_spanner_emulator(project_id: str, instance_id: str, database_id: str):
    client = spanner.Client(
        project=project_id,
        client_options={"api_endpoint": "localhost:9020"},
    )
    database = client.instance(instance_id).database(database_id)
    ls_request = spanner_v1.ListSessionsRequest(database=database.name)
    sessions = database.spanner_api.list_sessions(request=ls_request)

    for session in sessions:
        try:
            begin_request = spanner_v1.BeginTransactionRequest(
                session=session.name,
                options=spanner_v1.TransactionOptions(
                    read_write=spanner_v1.TransactionOptions.ReadWrite()
                ),
            )
            transaction = database.spanner_api.begin_transaction(request=begin_request)

            rollback_request = spanner_v1.RollbackRequest(
                session=session.name,
                transaction_id=transaction.id,
            )
            database.spanner_api.rollback(request=rollback_request)
        except Exception as ex:
            logger.warning(ex)
```

**Comment by olavloite** [comment]
The next release (1.5.23) of the emulator will contain a change that should help with this problem:
1. Currently, the read/write transaction that grabs the exclusive lock for a database will hold on to it until it is committed or rolled back. Any new read/write transaction that attempts to start is directly aborted.
2. From the next release, a new read/write transaction will have a 20% probability of aborting the transaction that currently holds the lock, unless the current transaction is at that moment actively executing a statement.
3. A read/write transaction that is defined in a standard retry loop should therefore be able to abort the transaction that currently holds the lock, but is not executing any further statements. This will make sure that transactions are able to make progress, even if the thread/process that holds the exclusive lock for a database crashes.

**Comment by olavloite** [comment]
Version 1.5.23 has been released. This version has a 20% probability of aborting an existing transaction that holds the exclusive lock when a new one is started (unless the transaction holding the lock is actively executing a statement when the new transaction tries to start).
