### ISSUE TITLE
Unsupported Spanner DDL statement: CREATE SEQUENCE

### ISSUE THREAD

**Issue by credmond-git** [GoogleCloudPlatform/cloud-spanner-emulator#140]
Hi! It seems like CREATE SEQUENCE function is not supported by the emulator with version 1.5.11. Related to issue https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/135

How to reproduce

Run emulator:
docker run -p 9010:9010 -p 9020:9020 gcr.io/cloud-spanner-emulator/emulator:1.5.11

With the DDL:
CREATE SEQUENCE project_id_sequence OPTIONS (sequence_kind = 'bit_reversed_positive');

Run Flyway migrations then i get the error

INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE SEQUENCE project_id_sequence OPTIONS (sequence_kind = 'bit_reversed_positive') : Syntax error on line 1, column 8: Encountered 'SEQUENCE' while parsing: create_statement

**Comment by olavloite** [comment]
This is a known feature gap that is being worked on. We expect to ship this by the end of this year.

**Comment by vishwanath-mathapati-scope** [comment]
@olavloite Is the fix done on 1.5.13?

**Comment by olavloite** [comment]
> @olavloite Is the fix done on 1.5.13?

No, it has been added in 1.5.14, which is the latest release (last week).

**Comment by vishwanath-mathapati-scope** [comment]
@olavloite Thanks, I can see its working on 1.5.14
