### ISSUE TITLE
PG.NUMERIC comparison operetors return an error

### ISSUE THREAD

**Issue by skuruppu** [GoogleCloudPlatform/cloud-spanner-emulator#148]
Currently, if you try to execute the following query:

```
SELECT 1.0 = 2.0
```

the emulator will return the following error:

```
"Inputs to Equal must support equality comparison: PG.NUMERIC"
```

This is only relevant for v1.5.12 where we introduced the Spanner PostgreSQL interface support in the emulator.

There is a fix for this that will go out in the next release but I just wanted to report it here in case anyone runs into it.

**Comment by matthewjumpsoffbuildings** [comment]
Is this related to a bug I am seeing in the emulator where if I run the following SQL in the emulator:

```sql
select * from `notifications` where `notifiable_id` = "2f9179bf-870e-4ff4-acad-f02114b0e0c4" 
```

I get this error 
```
No matching signature for operator = for argument types: INT64, STRING. Supported signature: ANY = ANY
```

However if I run the same code in Spanner Studio on a real database it works fine?

**Comment by matthewjumpsoffbuildings** [comment]
Though in my case I am using the Google SQL, not the PostgreSQL mode, so maybe this is a separate thing?

**Comment by skuruppu** [comment]
As of the [v1.5.13 release](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.13), this issue is fixed.
