### ISSUE TITLE
Pre-built docker image v1.5.14 not supporting arm64

### ISSUE THREAD

**Issue by halnique** [GoogleCloudPlatform/cloud-spanner-emulator#157]
Same problem as described in #132 #145 has appeared again in v1.5.14.

https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/134#issuecomment-1756818826
> We'll look into whether it's feasible to publish all three at the same time to avoid this confusion.

I would appreciate it if you could give this a higher priority and work on it.

**Comment by pratickchokhani** [comment]
This issue is resolved.
