### ISSUE TITLE
Feature Request - Generated Columns

### ISSUE THREAD

**Issue by loremont** [GoogleCloudPlatform/cloud-spanner-emulator#17]
Now Cloud Spanner allows creation of generated columns.
https://cloud.google.com/spanner/docs/generated-column/how-to

Do you plan to add support for them?

**Comment by Vizerai** [comment]
Yes, generated columns will be supported in the next release which should come out within ~1 week.

**Comment by jacobdufault-google** [comment]
Added in b0c06e0e17cac56af7d3335c18dfb1a780ff89d4
