### ISSUE TITLE
Full-text search error.

### ISSUE THREAD

**Issue by jmbradshaw79** [GoogleCloudPlatform/cloud-spanner-emulator#183]
It seems the full text search capabilities are not currently functional in the emulator. 

When creating a table to start adding the feature, my local dev environment relying on the emulator fails. 
And example table:
```sql
CREATE TABLE T (
  Id STRING(20),
  Text STRING(MAX),
  Text_Tokens TOKENLIST AS (TOKENIZE_FULLTEXT(Text)) HIDDEN,
) PRIMARY KEY(Id);
```
errors with:
```
ddl_type_conversion.cc:238] INTERNAL: ZETASQL_RET_CHECK failure (backend/schema/updater/ddl_type_conversion.cc:238) false Unrecognized ddl::ColumnDefinition: column_name: "Text_Tokens" type: NONE proto_type_name: "TOKENLIST" hidden: true generated_column { expression: "(TOKENIZE_FULLTEXT(Text))"
```

**Comment by ed-irl** [comment]
Any update on whether this is scheduled to be added? The absence of this makes using this feature in well-tested code difficult.

**Comment by skuruppu** [comment]
We're planning to do an emulator release next week and it will include full-text search support. I will update here once the release is complete.

**Comment by skuruppu** [comment]
A quick update that the emulator release 1.5.25 is now available for AMD64 with full-text search support. I'm still working on the ARM64 release (should be complete within the next day) but hopefully the former will unblock some of you.

**Comment by skuruppu** [comment]
I will mark this as closed now since the release is complete.

Note that emulator full-text search support in gcloud will be rolled out in the next gcloud release.

Thanks for your patience.
