### ISSUE TITLE
emulator crashing with check-fail of LoadTimeZone

### ISSUE THREAD

**Issue by Michaelhobo** [GoogleCloudPlatform/cloud-spanner-emulator#19]
I'm running the spanner emulator process as a subprocess of a Go program, running on GCP's Container Optimized OS. It starts fine and is able to serve a bit of data - I can usually write some data and read from it within the next few minutes. Soon after, analyzer.cc crashes with this error:

```
2021-01-11 23:31:57  FATAL  analyzer.cc : 317 : Check failed: LoadTimeZone("America/Los_Angeles", &default_timezone_) 
2021-01-11 23:31:57  FATAL  analyzer.cc : 317 : Check failed: LoadTimeZone("America/Los_Angeles", &default_timezone_) 
2021/01/11 23:31:58 Spanner Emulator failed: signal: aborted (core dumped)
```

Originally, I thought this might be memory usage related, but I'm now running this on a 2 vCPU 8GB RAM VM, so I believe that shouldn't be a problem.

I don't really understand what causes this yet - any idea what this could be, or pointers on how to tackle this?

**Comment by Vizerai** [comment]
This is due to a missing dependency on tzdata. Make sure that is installed on the system you are running on.
This issue should be resolved in the next release.

**Comment by Michaelhobo** [comment]
When will the next release come out?

**Comment by Michaelhobo** [comment]
I can confirm that adding tzdata solved the problem for me, though. Since my host is dockerized w/ an ubuntu base image, I had to add a step to install the tzdata package.

**Comment by Vizerai** [comment]
The new version of the emulator has been released now. If you have your own setup that does not use our docker images you will have to make sure it has tzdata.

**Comment by Michaelhobo** [comment]
Thanks. I didn't realize the fix was in the docker image, not the binary. I guess my change was needed anyway, then.
