### ISSUE TITLE
Support named schamas

### ISSUE THREAD

**Issue by apstndb** [GoogleCloudPlatform/cloud-spanner-emulator#192]
https://cloud.google.com/spanner/docs/schema-and-data-model#named-schemas

It seems that [v1.25.0 have implementation of named schemas](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/compare/v1.5.24...v1.5.25), but [the release note](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.25) has no description about it.
What is the current status?

**Comment by skuruppu** [comment]
Really sorry about this mistake. You're completely right that named schemas are supported in the v1.2.25 release.

I updated the release notes. Thanks for flagging this.
