### ISSUE TITLE
Emulator Performance / Paralleism

### ISSUE THREAD

**Issue by bmhatfield** [GoogleCloudPlatform/cloud-spanner-emulator#2]
Hi there,

Thanks for creating the Spanner Emulator. This tool has been instrumental in improving the reliability of the code we write with Spanner.

However, as we have added tests which depend on the emulator, often doing small (less than 10 rows), self contained things, we've noticed that the performance of our overall test suite has degraded significantly. After some analysis, we believe we're being heavily limited by the emulator, with simple operations (2 three row inserts) taking 30s+

We completely understand the note in the readme explaining that the Emulator's performance is not comparable to that of Cloud Spanner, but we're finding that as-is, it's a bit more limiting than we had hoped.

We're working in Go, with tests written to set up new DBs as described [in the recommended test setup](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator#what-is-the-recommended-test-setup) section. We're careful to not create databases we aren't using. We clean up the DBs as tests complete using Go's `t.Cleanup()` and the AdminClient's `DropDatabase` operation. (We have enough tests using the emulator that we can't skip this cleanup step, or we get errors about too many databases).

To help frame what we're seeing, I've run our test suite at multiple parallelism levels, both with build and test parallelism tuned to different levels, as well as disabled entirely.

```
go test -p 2 ./...  171.80s user 33.24s system 106% cpu 3:11.84 total
go test -p 4 ./...  183.28s user 37.14s system 150% cpu 2:26.87 total
go test -p 8 ./...  205.39s user 44.78s system 178% cpu 2:20.04 total
go test -p 16 ./...  218.39s user 51.40s system 197% cpu 2:16.49 total
```

- By default, that `-p` value is set to GOMAXPROCS, which is the number of core-threads on your machine. So for the computer I am on, the default is `-p 16` for me (8 cores, 2 threads per core).
- In each of the test observations, the emulator was the dominant CPU usage on my mac, with `go test` mostly idle, as reported by `htop`.
- **The emulator appears to max out at about 100% of one core, even though I've dedicated 4 cores to the docker-for-mac VM that it's running in.**
- `-p 4` appears to be the last point at which there's a real gain in wall-clock time, demonstrating to me a clear concurrency bottleneck.
- I cleared the go test cache before each of those runs.
- The Emulator has this in it's documentation: "The emulator only allows one read-write transaction or schema change at a time. Any concurrent transaction will be aborted.". I'm not really sure what this means (ie, process wide, or per-DB?), but I have a hunch it's not good for running concurrent tests.
- Without the Spanner Emulator tests enabled (ie, by calling `t.SkipNow()`), our test suite takes about 30s.

Given those observations, what are some strategies we could take for getting our test time down? Are there performance or concurrency improvements for the emulator coming on the horizon?

Thank you!

**Comment by adirastogi** [comment]
The Emulator serializes operations against a single database and not across databases. However, database creation/deletion itself is serialized. So if each of your tests is creating/deleting a new database and is relatively short, then that could potentially be the concurrency bottleneck. 

To get around that, you could try to do the database creation and teardown before/after running your parallel test suite:

```
func TestSetupAndRunParallel(t *testing.T) {
    // <database setup code>
    // This Run will not return until its parallel subtests complete.
    t.Run("group", func(t *testing.T) {
        t.Run("Test1", parallelTest1)
        t.Run("Test2", parallelTest2)
        t.Run("Test3", parallelTest3)
    })
    // <database tear-down code>
}
```

**Comment by alapkarapurkar** [comment]
Thanks for the valuable feedback!

I wanted to additional clarify the "The emulator only allows one read-write transaction or schema change at a time. Any concurrent transaction will be aborted." part since "simple operations (2 three row inserts) taking 30s+" is not expected. 

"One transaction at a time" is a per-database restriction. Within a unit test, if you are running multiple transactions in parallel on the same database, only one of them will make progress. The others will be aborted. The client libraries will retry aborted transactions with exponential backoff which can account for long test times.

Is this (parallel transactions in a single unit test on a single DB) a pattern you are using in your unit-tests? (This will help us prioritize possible improvements).

**Comment by bmhatfield** [comment]
Thank you both for your responses!

As a result of @adirastogi's note, I did some investigation into how our tests are running and where the contention might be. It appears, for our use case, that the contention is primarily on database creates. Each database create takes about 1s, and when multiple happen at the same time, the time goes way up (likely due to aborts/retries, as you suggested).

Upon further analysis, we tend not to do parallel tests against the same DB, but we do parallelize across DBs (creating a new DB for each test/set).

Of the two cases (parallel DB creates, parallel transactions within a DB), it appears that improving/supporting parallel DB creates would be significantly more valuable for alleviating the issue we're seeing.

**Comment by bmhatfield** [comment]
An update on experiments and observations: I was able to significantly improve the real-time running time of my test suite as well as the reported test timings by running 4 copies of the emulator container and randomly balancing tests across them. While I can make this work for us temporarily, in my opinion, this approach is a bit of a "hack" and subject to various kinds of brittleness.

I believe this further indicates that improving the concurrency of DB creates would be very helpful, especially when considered in the context of the Readme.md recommendation that "creating databases is cheap".

Thank you!

**Comment by alapkarapurkar** [comment]
Thanks for the detailed observations - CreateDatabase calls are indeed serialized process-wide right now and this will be fixed in the next release which should help with running parallel tests.

**Comment by bmhatfield** [comment]
That's very exciting! I think that will really help us! Thank you for the update.

**Comment by bmhatfield** [comment]
@adirastogi @alapkarapurkar I noticed 1.1.0 land in GCR! We upgraded our emulator version configs, and our emulator tests now run more than 50% faster, and fully make use of the compute resources we've assigned to the emulator! Thank you!

**Comment by Vizerai** [comment]
The repository has been updated with version 1.1.0 now.
