### ISSUE TITLE
NULL_FILTERED INDEX error message is likely wrong

### ISSUE THREAD

**Issue by Dakatan** [GoogleCloudPlatform/cloud-spanner-emulator#20]
Im using `NUULL_FILTERED INDEX`, and emulator return this message.

```
The emulator is not able to determine whether the null filtered index <SomeIndex> can be used to answer this 
query as it may filter out nulls that may be required to answer the query. Please test this query against Cloud Spanner. If you 
confirm against Cloud Spanner that the null filtered index can be used to answer the query, set the hint 
@{spanner_emulator.disable_query_null_filtered_index_check=false} on the table to bypass this check in the emulator. This 
hint will be ignored by the production Cloud Spanner service and the emulator will accept the query and return a valid result 
when it is run with the check disabled.
```

I think table hint is `@{spanner_emulator.disable_query_null_filtered_index_check=true}`, not `@{spanner_emulator.disable_query_null_filtered_index_check=false}`.

**Comment by Nearhan** [comment]
I am using spanner emulator to do integration testing and it would be great to be able to turn this off in config instead of modifying the query by adding `spanner_emulator.disable_query_null_filtered_index_check=true`.  Would love help on this. @Dakatan ?

**Comment by Vizerai** [comment]
@Dakatan - Yes, I think you are correct. I will update the error message.
