### ISSUE TITLE
EXCEPT operator not supported

### ISSUE THREAD

**Issue by roybos** [GoogleCloudPlatform/cloud-spanner-emulator#26]
We try to use the EXCEPT operator to exclude some columns from a query, but we get an exception that the operation is not supported. 
```INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: SELECT * EXCEPT is not supported [at 1:8]```
On Spanner on GCP the query just works, i.e. `SELECT * EXCEPT (my_column) FROM my_table;`
ZetaSQL also support EXCEPT: https://github.com/google/zetasql/blob/master/docs/query-syntax.md#select--except

Is this a bug?
If not, where can we find the list of supported SQL statements.

**Comment by Vizerai** [comment]
Yes, the emulator does support this through zetasql, but it was not enabled. We have now enabled it, which will be in the next release.

**Comment by roybos** [comment]
Thanks for the fast update!
When is the next release planned?

**Comment by Vizerai** [comment]
Probably within the next few weeks.

**Comment by jacobdufault-google** [comment]
The fix for this is included in the 1.3 release (738d9cc62038a84981f749acf9b43d86c72fbf12).
