### ISSUE TITLE
Support ROW DELETION POLICY in create/alter table

### ISSUE THREAD

**Issue by caseyduquettesc** [GoogleCloudPlatform/cloud-spanner-emulator#32]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: MacOS 11.5
3. Java version: 11
4. spanner version(s): 6.10.1

#### Steps to reproduce

  1. Create or alter table schema with `ROW DELETION POLICY` 
  2. ?

#### Code example

```kt
spanner
    .databaseAdminClient
    .createDatabase(
        instanceName,
        databaseName,
        listOf(
            "CREATE TABLE my_table " +
            "(" +
            "StreamId BYTES(16) NOT NULL, " +
            "LastUpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)" +
            ") " +
            "PRIMARY KEY (StreamId),\n" +
            "ROW DELETION POLICY (OLDER_THAN(LastUpdateTime, INTERVAL 30 DAY))",
        )
    )
    .get(10, TimeUnit.SECONDS)
```

#### Stack trace
```
com.google.cloud.spanner.SpannerException: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE TABLE my_table (StreamId BYTES(16) NOT NULL, LastUpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)) PRIMARY KEY (StreamId),
ROW DELETION POLICY (OLDER_THAN(LastUpdateTime, INTERVAL 30 DAY)) : Syntax error on line 1, column 148: Expecting 'EOF' but found ','
       com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
       com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:421)
       com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:95)
       com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:68)
       com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:133)
```

#### External references such as API reference guides

- https://cloud.google.com/spanner/docs/ttl#managing_ttl

#### Any additional information below

Am using the Java cloud spanner library, but I suspect the issue lies with the emulator?

I don't mind if the statement is a noop, but it'd be nice to use the same DDL in the tests and actual.

**Comment by majelbstoat** [comment]
A reasonable first step for our purposes would be to not fail on on the parsing but just make it a no-op.

**Comment by patrickmeiring** [comment]
I work on Chrome Core Infra.

This issue is making it harder to track the current version of Schema for some of our projects, as we have to track the DDL supported by cloud spanner emulator separately from that supported by real Spanner.

**Comment by apstndb** [comment]
Is this issue resolved?
https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.4.1
> Added support for row deletion policy syntax. The syntax will be treated as no op.

**Comment by qbarlas** [comment]
Yes it is.  We are currently using cloud sdk 381.0.0 emulators docker image without removing theses instructions from the DDL anymore.

**Comment by kylechadha** [comment]
@qbarlas Just a heads up this still breaks for us on 1.4.1:

```
ALTER TABLE someTable ADD ROW DELETION POLICY ( OLDER_THAN ( delColumn, INTERVAL 90 DAY ));
 (details: rpc error: code = Internal desc = ZETASQL_RET_CHECK failure (backend/schema/updater/schema_updater.cc:1340) alter_table.has_alter_column() || alter_table.has_alter_constraint()
```

Upgrading to 1.4.2 fixes the above failure, but introduces a new one on a previously working migration:
```
CREATE TABLE differentTable (
  pkColumn STRING(64) NOT NULL,
  ...
  delColumn TIMESTAMP,
) PRIMARY KEY(pkColumn),
  ROW DELETION POLICY ( OLDER_THAN ( delColumn, INTERVAL 1 DAY ));
 (details: rpc error: code = InvalidArgument desc = ROW DELETION POLICY will break if drop/alter column named delColumn in table differentTable. Row Deletion Policy must be set on column of type TIMESTAMP.)
```

cc: @jhai420

**Comment by j4ckcyw** [comment]
> @qbarlas Just a heads up this still breaks for us on 1.4.1:
> 
> ```
> ALTER TABLE someTable ADD ROW DELETION POLICY ( OLDER_THAN ( delColumn, INTERVAL 90 DAY ));
>  (details: rpc error: code = Internal desc = ZETASQL_RET_CHECK failure (backend/schema/updater/schema_updater.cc:1340) alter_table.has_alter_column() || alter_table.has_alter_constraint()
> ```
> 
> Upgrading to 1.4.2 fixes the above failure, but introduces a new one on a previously working migration:
> 
> ```
> CREATE TABLE differentTable (
>   pkColumn STRING(64) NOT NULL,
>   ...
>   delColumn TIMESTAMP,
> ) PRIMARY KEY(pkColumn),
>   ROW DELETION POLICY ( OLDER_THAN ( delColumn, INTERVAL 1 DAY ));
>  (details: rpc error: code = InvalidArgument desc = ROW DELETION POLICY will break if drop/alter column named delColumn in table differentTable. Row Deletion Policy must be set on column of type TIMESTAMP.)
> ```
> 
> cc: @jhai420

@kylechadha Is this still broken in the latest version? Do you have a minimal repro?

**Comment by kylechadha** [comment]
@j4ckcyw Thanks for following up. Currently on 1.4.9 and no issues 👍🏽
