### ISSUE TITLE
docs: CHECK constraints are not listed as unsupported

### ISSUE THREAD

**Issue by olavloite** [GoogleCloudPlatform/cloud-spanner-emulator#34]
When trying to add a `CHECK` constraint to a table, the emulator will respond with an error with code `Unimplemented` as it is currently not supported. This limitation is however not listed under the notable limitations here: https://github.com/GoogleCloudPlatform/cloud-spanner-emulator#features-and-limitations

**Comment by jacobdufault-google** [comment]
CHECK constraint support should be available now as part of the 1.3 release (738d9cc62038a84981f749acf9b43d86c72fbf12).
