### ISSUE TITLE
Add support for JSON data types

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/cloud-spanner-emulator#37]
Would be very helpful to have JSON data types for integration testing.

**Comment by flunderpero** [comment]
Please keep the emulator in sync with the Spanner feature set. This one here and #32 are slowing down our development quite a bit because we have to build workarounds.

**Comment by kanekv** [comment]
This issue prevents from using json types in our project. Even though spanner itself supports them, we are already relying too much on emulator for local development.

**Comment by sam-white** [comment]
This issue is currently blocking further development for us as we have a data model strongly reliant on the JSON column type.

**Comment by kylechadha** [comment]
Looks like this is fixed? https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/pull/61/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR8 strange way to release :)

**Comment by pfa230** [comment]
This should be supported in [1.4.0 release](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.4.0).
