### ISSUE TITLE
Attempting to create a table that includes a `CHECK` constraint returns grpc `UNIMPLEMENTED`

### ISSUE THREAD

**Issue by MusikPolice** [GoogleCloudPlatform/cloud-spanner-emulator#41]
Google Cloud Spanner supports [a `CHECK` constraint](https://cloud.google.com/spanner/docs/check-constraint/how-to), which allows the developer to add a constraint to a table that specifies some boolean condition that each row must satisfy. 

Suppose that I create a new table called `Foo` that has two nullable columns, and the expectation is that one of those columns will be non-null at any given time. I could create this table with the following SQL:
```
CREATE TABLE Foo (
    fooId STRING(255) NOT NULL,
    someId STRING(255),
    someOtherId STRING(255),
    CONSTRAINT someId_or_someOtherId_specified CHECK (someId IS NOT NULL OR someOtherId IS NOT NULL)
) PRIMARY KEY (
    fooId
)
```

In this case, the `someId_or_someOtherId` constraint will be evaluated whenever a row is inserted or updated in the `Foo` table. The operation will fail if the constraint evaluates to `FALSE`.

Problem is, the emulator does not support check constraints (this limitation [is documented in the emulator readme](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/master/README.md)) but rather than silently ignoring the constraint when data is inserted or updated, the emulator refuses to allow me to create the constraint in the first place. 

When I try to run a Flyway migration against the emulator that creates a table with a `CHECK` constraint, I get an error that looks like this:
```
Execution failed for task ':flyway:flywayMigrate'.
  Error occurred while executing flywayMigrate
  Migration failed !
  Migration failed !
  com.google.cloud.spanner.SpannerException: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Check Constraint is not implemented.
  UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Check Constraint is not implemented.
  UNIMPLEMENTED: Check Constraint is not implemented.
```

Because my project uses this emulator for local development, I can't make use `CHECK` constraints in my schema, because doing so fails locally, even though these constraints **are fully supported by real Spanner**. 

This behaviour is not consistent with the behaviour that I see when making use of other Spanner functionality that the emulator does not support. As an example, I can create secondary indexes in my schema, even though [the emulator readme](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/master/README.md) says that they are not supported.

Is it possible for the emulator to silently ignore `CHECK` constraints in the same way that it ignores secondary indexes? This would allow me to include them in my schema, even though they are not evaluated when running test code against the emulator.

**Comment by jacobdufault-google** [comment]
What version of the emulator are you using? CHECK constraints should be supported in the latest release, 1.3.0. The section of the README you're linking to is for supported features; the unsupported ones are right below that list.

**Comment by MusikPolice** [comment]
Upgraded to 1.3.0 and the issue was resolved. Thanks @jacobdufault-google !
