### ISSUE TITLE
Add support for table_type in information_schema.tables

### ISSUE THREAD

**Issue by vi3k6i5** [GoogleCloudPlatform/cloud-spanner-emulator#43]
This query is failing with emulator

```
SELECT
  t.table_name, t.table_type
FROM
  information_schema.tables AS t
```

**Comment by pfa230** [comment]
This should be supported in [1.4.0 release](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.4.0).
