### ISSUE TITLE
Can't correct clone on not Case-sensitive OSes such as macOS

### ISSUE THREAD

**Issue by zchee** [GoogleCloudPlatform/cloud-spanner-emulator#5]
Can't correct `git clone` on **not Case-sensitive** OSes such as macOS. Always have diff when after the just cloned this repository. (means deleted `build` directory)
The root cause is the `BUILD` bazel build file is conflicted `build` directory.

In the background, macOS users usually use APFS **not Case-sensitive** disk type. It's the default option at least after the macOS Catalina. Old _"Mac OS Extended (HFS+)"_ disk type too. Might be Apple's recommendation.
This problem such as the same as can't build Linux kernel on macOS.

Actually, that's a not cloud-spanner-emulator repository bug, but we happy if repository maintainers care to not Case-sensitive OSes.

---

Fixed way is just simply, rename `BUILD` to `BUILD.bazel`. The bazel command also parses this file name by default.
Like this diff: https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/compare/master...zchee:macOS-case-sensitive
Noticed
> We are currently not accepting external code contributions to this project.

so I don't send PR but I hope this diff will be helpful to you.

Thanks.

**Comment by alapkarapurkar** [comment]
Thanks for the report! This will be fixed with the next release/push.

**Comment by Vizerai** [comment]
This is fixed now with version 1.1.0

**Comment by zchee** [comment]
@Vizerai thanks for fix!! closed.
