### ISSUE TITLE
Max Joins does not match real spanner documentation

### ISSUE THREAD

**Issue by RoryQ** [GoogleCloudPlatform/cloud-spanner-emulator#52]
The spanner documentation says the join limits for querying is 20
https://cloud.google.com/spanner/quotas#query_limits

However the emulator has this set for 15
https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/a10bf75fefc5b47e75182df1acad73a0db5c7040/backend/query/feature_filter/query_size_limits_checker.cc#L46

Can this (~~and other limits~~ other limits look in sync) be updated to match the documentation?

**Comment by pfa230** [comment]
This should be fixed in [1.4.0 release](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.4.0).
