### ISSUE TITLE
Feature Request - Add support for Numeric Types

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/cloud-spanner-emulator#6]
Spanner recently released support for the `NUMERIC` type: https://cloud.google.com/spanner/docs/data-types#numeric_type

Could support for numeric columns be added to the emulator?

**Comment by Vizerai** [comment]
Support for numeric type is actively being worked on. It will be added in
the next release of the emulator.

- Jim

**Comment by juztin** [comment]
I hate to ask, but just trying to plan out some work.
As there's only a single release, I'm curious as to the release schedule, or if there's a forecast for release.
_(mainly just trying to determine if this is something I can wait on, or work around)_

**Comment by adirastogi** [comment]
Currently, our aim is to make newly features available in the Emulator within 6 months of their launch in the production service. But we are working towards achieving a faster and predictable release cadence for the Emulator

**Comment by jacobdufault-google** [comment]
Added in b0c06e0e17cac56af7d3335c18dfb1a780ff89d4
