### ISSUE TITLE
Cloud Spanner Emulator version 1.4.1 (linux binary) no longer works on CentOS Stream 8

### ISSUE THREAD

**Issue by story-of-code** [GoogleCloudPlatform/cloud-spanner-emulator#65]
### Summary
We are running CentOS Stream 8 in our environment.
Prior to the most recently released version, `1.4.1`, Spanner Emulator was running perfectly on CentOS 8.
Starting with `1.4.1` an attempt to run `gateway_main` on CentOS 8 results in an error:
```
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/1.4.1/emulator_main)
2022/02/22 02:07:31 gateway.go:107: Shutting down gateway server since grpc server is terminated.
```

According to the documentation in this repository, it should work:
> Note that this binary is not fully static, but has been tested on Ubuntu 16.04/18.04, **CentOS 8, RHEL 8**, and Debian 9/10.

#### Possible root cause

It appears like the most recent version of binaries was built/linked on a machine with `GLIBCXX_3.4.26` support, with no hard linking to a specific GLIBCXX version. `GLIBCXX_3.4.26` symbols are supported as part of `libstdc++.so.6.0.26` binary which is part of the `GCC 9.1.0` ([source, GCC versioning documentation](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)). CentOS 8/RHEL 8 is shipped with GCC 8 so binaries built for `GLIBCXX_3.4.26` are not going to work on CentOS 8/RHEL 8.

### Steps to reproduce
The easiest way to reproduce this issue would be to create a CentOS 8 docker container, download Spanner Emulator to it, and attempt to start it.

#### Dockerfile
I've defined the following `Dockerfile` which uses the official CentOS Stream 8 docker image and installs `wget` to download the emulator
```
FROM quay.io/centos/centos:stream

RUN yum install -y wget

ENTRYPOINT ["tail", "-f", "/dev/null"]
```

#### Preparing the test environment
To confirm that the issue is only present in the most recent version I'm going to run affected and unaffected versions on the same container.

To prepare the container I'm going to create two folders under `home` (one for `1.4.0` version and one for `1.4.1`), download two different versions of the emulator and unpack them to corresponding folders:
```
cd ~
mkdir 1.4.0
mkdir 1.4.1
wget https://storage.googleapis.com/cloud-spanner-emulator/releases/1.4.0/cloud-spanner-emulator_linux_amd64-1.4.0.tar.gz
wget https://storage.googleapis.com/cloud-spanner-emulator/releases/1.4.1/cloud-spanner-emulator_linux_amd64-1.4.1.tar.gz
tar zxvf cloud-spanner-emulator_linux_amd64-1.4.0.tar.gz -C ./1.4.0
tar zxvf cloud-spanner-emulator_linux_amd64-1.4.1.tar.gz -C ./1.4.1
```

#### Running emulator
First I'm going to run the `1.4.0` version to confirm that it works just fine:
```
./1.4.0/gateway_main --hostname 0.0.0.0
```
Output:
```
2022/02/22 02:07:07 gateway.go:140: Cloud Spanner emulator running.
2022/02/22 02:07:07 gateway.go:141: REST server listening at 0.0.0.0:9020
2022/02/22 02:07:07 gateway.go:142: gRPC server listening at 0.0.0.0:9010
```

Now I'm going to try and run the `1.4.1` version and see it fail:
```
./1.4.1/gateway_main --hostname 0.0.0.0
```
Output:
```
/root/1.4.1/emulator_main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/1.4.1/emulator_main)
2022/02/22 02:07:31 gateway.go:107: Shutting down gateway server since grpc server is terminated.
```
Here is a screenshot of this reproduction example:
![image](https://user-images.githubusercontent.com/63533332/155052662-12806fa7-1b86-41a4-89c9-cb729e35c355.png)

**Comment by Vizerai** [comment]
Version 1.4.2 will revert back to gcc8. This should be pushed out in a few weeks.  In the meantime you will have to use version 1.4.0 on CentOS Stream 8.

**Comment by Vizerai** [comment]
v1.4.2 has been released. This uses gcc8.
