### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by rregitsky** [GoogleCloudPlatform/cloud-spanner-emulator#69]
Our team is attempting to use a PostgreSQL Spanner database and discovered that there is currently no support for PostgreSQL on the Emulator. This lack of parity makes it prohibitively difficult to do local development in our environment.

**Comment by jdwyah** [comment]
Would be nice to add this to the emulator or PostgreSQL docs. Been banging my head on this for a bit. 

Is the answer to just run Postgres locally, not the emulator? And then use JDBC to connect?

**Comment by skuruppu** [comment]
Thanks for reporting the issue. This is definitely something we're working on. But I don't have any timelines yet on when we'll be publishing the emulator support.

In the meatime, I can think of two options for local development.

1. Run Postgres locally as @jdwyah mentioned. But note that [some Postgres features are not supported in Spanner](https://cloud.google.com/spanner/docs/reference/postgresql/overview) and some Spanner features like interleaved tables are not supported in Postgres.
2. This may not be an option for everyone but you could also use a [granular instance](https://cloud.google.com/blog/products/databases/use-spanner-at-low-cost-with-granular-instance-sizing).

**Comment by skuruppu** [comment]
Thanks for your patience.

PostgreSQL support was released in [v1.5.12](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.12).

Please file an issue if you run into any issues. There is a known issue that I reported in #148. Above that, please also check out the [Features and Limitations section](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/tree/master/third_party/spanner_pg#features-and-limitations).
