### ISSUE TITLE
Memory Leak + Performance Decrease per Connection

### ISSUE THREAD

**Issue by vitaminmoo** [GoogleCloudPlatform/cloud-spanner-emulator#72]
It looks like there's a leak in the emulator - If you do a bunch of reads, but use new connections, the emulator gets slower and slower to respond, regardless of what your queries are.

Deleting rows, dropping tables, deleting the database, and deleting the instance has no effect on performance after that - Only stopping the process causes it to get speedy again.

Below is an example of a naïve test case - Running this results in 10-20ms additional latency per query per 100 connections, with no upper bound until your machine runs out of memory. Moving the client creation to have the connection persist removes the impact on latency.

Some incompetent digging in some core files shows these two symbols as possibly notable:
```
(gdb) info symbol 0x33a0280
grpc_core::kNoopRefcount in section .bss of /home/graham/google-cloud-sdk/bin/cloud_spanner_emulator/emulator_main
(gdb) info symbol 0x301b6e0
grpc_core::ParsedMetadata<grpc_core::MetadataMap<grpc_core::GrpcTimeoutMetadata, grpc_core::TeMetadata, grpc_core::UserAgentMetadata, grpc_core::GrpcMessageMetadata, grpc_core::
HostMetadata, grpc_core::XEndpointLoadMetricsBinMetadata, grpc_core::GrpcServerStatsBinMetadata, grpc_core::GrpcTraceBinMetadata, grpc_core::GrpcTagsBinMetadata> >::EmptyVTable(
)::vtable in section .rodata of /home/graham/google-cloud-sdk/bin/cloud_spanner_emulator/emulator_main
```

```golang
package main

import (
	"context"
	"fmt"
	"time"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/iterator"
)

func main() {
	ctx := context.Background()
	for i := 1; i < 10000; i++ {
		t := time.Now()
		client, err := spanner.NewClient(ctx, "projects/test/instances/instance0/databases/database0")
		if err != nil {
			panic(err)
		}

		stmt := spanner.Statement{SQL: `SELECT count(1) FROM table`}
		iter := client.Single().Query(ctx, stmt)
		defer iter.Stop()
		for {
			_, err := iter.Next()
			if err == iterator.Done {
				break
			}
			if err != nil {
				panic(err)
			}
		}
		client.Close()
		if i%100 == 1 {
			fmt.Println(time.Since(t))
		}
	}
}
```

**Comment by artlo** [comment]
The same issue, but without creating new connections. The connection is reused for all queries and it gets slower, but after some time it's fast again, so it looks like a wave diagram.
I tried to limit the number of connection with SessionPoolConfig. It helps but the peaks still present with smaller amplitude, then without session pool limitation.

**Comment by pilotofbalance** [comment]
same for me, running as docker image, batch insert, one connection, after 10k inserts slowing down till it dies with DeadlineExceeded error...

**Comment by epsniff** [comment]
I experience the same issue.

**Comment by gauravpurohit06** [comment]
We are prioritising the issue and will get back on it soon.

**Comment by fenilfadadu** [comment]
@vitaminmoo One potential issue that I see in the code that your shared is `defer iter.Stop()` line. This is causing the corresponding connection resources to not get freed till the end of the function, i.e., end of the process in this case. I added one additional log line in your code printing the allocated memory, and as you can see below, allocated memory do increase, along with System memory.

```
fenilf@fct:~/emulator$ go run memory.go
381.686318ms
Alloc = 2 MiB   TotalAlloc = 4 MiB      Sys = 17 MiB    NumGC = 2
471.666737ms
Alloc = 25 MiB  TotalAlloc = 72 MiB     Sys = 42 MiB    NumGC = 14
355.794848ms
Alloc = 35 MiB  TotalAlloc = 139 MiB    Sys = 66 MiB    NumGC = 18
436.049144ms
Alloc = 52 MiB  TotalAlloc = 205 MiB    Sys = 91 MiB    NumGC = 20
427.967979ms
Alloc = 87 MiB  TotalAlloc = 272 MiB    Sys = 107 MiB   NumGC = 21
387.804399ms
Alloc = 115 MiB TotalAlloc = 339 MiB    Sys = 136 MiB   NumGC = 22
427.957321ms
Alloc = 135 MiB TotalAlloc = 407 MiB    Sys = 157 MiB   NumGC = 23
460.003787ms
Alloc = 145 MiB TotalAlloc = 473 MiB    Sys = 169 MiB   NumGC = 24
```

But if I remove `defer iter.Stop()` and add an explicit `iter.Stop()` just before the `client.Close()`, I don't see any memory build-up.
```
fenilf@fct:~/emulator$ go run memory.go
300.120828ms
Alloc = 2 MiB   TotalAlloc = 4 MiB      Sys = 17 MiB    NumGC = 2
476.052066ms
Alloc = 2 MiB   TotalAlloc = 72 MiB     Sys = 21 MiB    NumGC = 42
539.571779ms
Alloc = 4 MiB   TotalAlloc = 139 MiB    Sys = 21 MiB    NumGC = 82
504.304514ms
Alloc = 3 MiB   TotalAlloc = 207 MiB    Sys = 21 MiB    NumGC = 123
500.139273ms
Alloc = 3 MiB   TotalAlloc = 275 MiB    Sys = 21 MiB    NumGC = 164
499.971207ms
Alloc = 3 MiB   TotalAlloc = 343 MiB    Sys = 21 MiB    NumGC = 205
508.008334ms
Alloc = 4 MiB   TotalAlloc = 410 MiB    Sys = 21 MiB    NumGC = 245
496.926065ms
```

Additionally, I don't see any other issues after this fix. @artlo, @epsniff, @flunderpero can you please share reproducible examples of issues from your end if you are still facing the issue?

@pilotofbalance I tried inserting 100k rows. It definitely gets slower but I don't see emulator dying. Can you pease share a reproducible example? Also the observed slowness is not very much of an issue as the emulator is supposed to be used for local unit testing of applications targeting Spanner. It is not intended to be performant.

Thanks!

**Comment by vitaminmoo** [comment]
@fenilfadadu This ticket is about a leak in the emulator, not the example client code being correct - If you run the client code twice, the slowness in the emulator does not start over.

The progressive slowness of the emulator has a real negative impact, as "local tests" does not imply a quantity of requests that is acceptable to do against it. We do not expect the emulator to accurately portray spanner's performance, but we expect it to continue functioning in a usable manner for the duration of our tests, without having to restart it.

**Comment by pilotofbalance** [comment]
@fenilfadadu I agree that for testing purposes I should not care about performance, but my issue is that Spanner Emulator crashes only just after 10k inserts with "**DeadlineExceeded**" exception. 

- Here is my GO code example to reproduce this issue:  https://github.com/pilotofbalance/spanner-emulator-worker/blob/main/main.go  
- I'm running this executable from bash script https://github.com/pilotofbalance/spanner-emulator-worker/blob/main/init-spanner.sh 
- After docker container initialized with https://github.com/pilotofbalance/spanner-emulator-worker/blob/main/Dockerfile

**Comment by fenilfadadu** [comment]
@vitaminmoo My point was that I'm not seeing emulator getting slower with the example code that you shared. What I was trying to point out was a plausible Memory-leak like scenario with a potential issue in the example code. 

I also did some further experiments. The progressive slowness that we observe comes from accumulating more and more data into emulator; latencies get reset when you reset the data. We also don't see slowness based on quantity of requests. Progressive slowness is also a broad area. We are not aware of any issues which goes aways with emulator restart. If you can provide specific use cases/examples/numbers we can provide faster relief by prioritising those issues.

**Comment by vitaminmoo** [comment]
I will have to re-run my tests with the latest release, which appears to have some dependency and build updates. I'll update with results.

**Comment by fenilfadadu** [comment]
@pilotofbalance apologies I missed to updated on this. The issue seems to be that batch insert of 1000 rows is slow on emulator and it gets gradually worst with more data in emulator.

Although we don't recommend using emulator for such heavy operations, we are doing best effort optimisations to make such queries faster than before.

Your issue doesn't really fit into the original issue of Memory Leak. I'll open another issue where we can independently track this.

**Comment by kt81** [comment]
Hi, @fenilfadadu.
I have created a complete test project to test @vitaminmoo's sample code.
https://github.com/kt81/spanner-emu-tester

From the results of the run, it looks reproducible.
(But as for memory leaks, I couldn't figure it out.)

```console
...
$ make run
13.6603ms
17.372299ms
31.821499ms
46.6992ms
55.764599ms
70.637199ms
83.588399ms
92.9404ms
107.0446ms
116.8905ms
128.591101ms
146.4209ms
153.661801ms
166.057102ms
...
```
(docker in wsl2)
