### ISSUE TITLE
CHANGELOG.md gone

### ISSUE THREAD

**Issue by adg** [GoogleCloudPlatform/cloud-spanner-emulator#82]
The latest Copybara import deleted `CHANGELOG.md` (see #81). Was that intentional? The previous import (#79) added more entries to it.

**Comment by gauravpurohit06** [comment]
Thanks but the remove was intentional as we already have release summary on [Releases] (https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases) tab.
