### ISSUE TITLE
README.md has outdated version strings

### ISSUE THREAD

**Issue by adg** [GoogleCloudPlatform/cloud-spanner-emulator#83]
The "Quickstart" instructions in `README.md` instruct the user to set `VERSION=1.4.2`. Should these strings be updated to the latest release?

**Comment by gauravpurohit06** [comment]
README.md is just for quick reference, we will try to keep it to the latest version but there is no guarantee in the near future as we don't have any automation on it. To check release version please refer [RELEASE](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases)
