### ISSUE TITLE
Document macOS and linux/arm64 support

### ISSUE THREAD

**Issue by adg** [GoogleCloudPlatform/cloud-spanner-emulator#84]
Issue #29 suggests that it is possible to build the emulator for ARM machines, and that it should run on M1 macs (as well as Linux ARM64 machines? not sure). There should be some documentation in `README.md` (or elsewhere) that explains the supported platforms and how to produce builds for those platforms.

**Comment by bmhatfield** [comment]
I'd also like to suggest publishing multi-platform container images - this would let folks just follow the docker instructions directly, rather than needing to build and host the container images themselves.

**Comment by eriklindgren** [comment]
I'm pretty sure that's what they already did @bmhatfield (though I agree some docs would be nice). When I pull the latest version of `gcr.io/cloud-spanner-emulator/emulator` on my M1 Pro MacBook and `docker inspect` it, the architecture of the image is `arm64`. If I do the same with the last version of the image (`gcr.io/cloud-spanner-emulator/emulator:1.4.5`) the architecture is `amd64`.

I also did a really simple performance comparison on a pretty database-intensive part of our test suite:
`gcr.io/cloud-spanner-emulator/emulator:1.4.6` -> 7.76s
`gcr.io/cloud-spanner-emulator/emulator:1.4.5` -> 13.77s

So v1.4.6 (arm64) is almost twice as fast as v1.4.5 (amd64) on my machine in this case. Nice!

**Comment by bmhatfield** [comment]
Interesting - this did not appear to be the case to me initially. 

However, I just re-pulled the image for 1.4.6 and Docker saw that there was a difference. I now see `arm64` layers. The manifest date is also updated slightly: `2022-09-27T08:23:04.2339785Z`. I must have just been early to the show in my excitement!

**Comment by gauravsnj** [comment]
We've now updated the `readme.md` file to say that we support arm64. There will be 3 manifests file for every release. The first one will try to detect the architecture and based on that it will automatically use either the arm64 manifest or the amd one.
