### ISSUE TITLE
Enable setting of `enable_column_default_values` feature flag

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/cloud-spanner-emulator#87]
Perhaps this is already possible and I just don't see how but could we expose setting this feature flag? I'm developing a new driver for an open source project and lack of DEFAULT support in DDL is getting in the way (even if the support is not complete this would be preferable to alterative workarounds).

**Comment by gauravpurohit06** [comment]
Thanks @tmc  for reaching out, the feature is under development and the issue is already been tracked on https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/71.

**Comment by tmc** [comment]
@gauravpurohit06 sort of.. this flag exists in the code but is not exposed. Is it the intent/policy here to only enable flags once the underlying feature is stable?
