### ISSUE TITLE
Feature Request: Add statement hint to disable DDL statement in emulator.

### ISSUE THREAD

**Issue by hughack** [GoogleCloudPlatform/cloud-spanner-emulator#93]
There are existing statement hints for the emulator, like:
```
@{spanner_emulator.disable_query_partitionability_check=true}
```

This feature request is to add a hint that will cause the emulator to skip a statement completely. E.g.:

```
@{spanner_emulator.skip_query=true}
```

This can be useful for a number of reasons, including:

- A statement is not required in testing.
- There is a lag between features being added to cloud Spanner and being added in the emulator. This means SQL scripts can't be used in the emulator despite them being valid. Emulator users need to create separate scripts and workarounds to handle it, which would be simplified by supporting a statement hint like this.

**Comment by gauravpurohit06** [comment]
Thanks @hughack  for logging the request, adding the hint would be helpful from customer point of view as there are couple of gaps between emulator and cloud spanner. We will evaluate the feasibility of solution and get back.

**Comment by gauravpurohit06** [comment]
The feature won't be supported  as it will cause Emulator's feature parity to widen as customers have a way to disable features.
