### ISSUE TITLE
env-init with dockerized spanner emulator

### ISSUE THREAD

**Issue by avinash-sonawane-searce** [GoogleCloudPlatform/cloud-spanner-emulator#95]
Hello!

Is `gcloud emulators spanner env-init` meant to be used with local spanner emulator only or can it also be used with dockerized spanner emulator?

When I try to run env-init with dockerized spanner emulator, it tries to look for env.yaml in host's data_dir.

```
$ docker run --rm -p 9010:9010 -p 9020:9020 -d --name spanner-dev gcr.io/cloud-spanner-emulator/emulator
e49f74167b2b758e17f8365df4a7de13da9264ad4c5fc70f8713ce8f2e072a40
$ gcloud config set api_endpoint_overrides/spanner http://localhost:9020/
Updated property [api_endpoint_overrides/spanner].
$ gcloud emulators spanner env-init
ERROR: (gcloud.emulators.spanner.env-init) Unable to find env.yaml in the data_dir [/home/avinashsonawane/.config/gcloud/emulators/spanner]. Please ensure you have started the appropriate emulator.
$ uname -io
x86_64 GNU/Linux
```

**Comment by gauravsnj** [comment]
Its only for local spanner. For dockerized spanner emulator, this is not needed. More details available [here](https://cloud.google.com/spanner/docs/emulator#use-gcloud)
