### ISSUE TITLE
Pre-built binary for ARM

### ISSUE THREAD

**Issue by nghialv** [GoogleCloudPlatform/cloud-spanner-emulator#96]
Hello,

As the [readme](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator#via-pre-built-linux-binaries), the pre-built binary for AMD can be downloaded here.

`https://storage.googleapis.com/cloud-spanner-emulator/releases/${VERSION}/cloud-spanner-emulator_linux_amd64-${VERSION}.tar.gz`

Could you tell me where the the path for ARM one?

**Comment by gauravsnj** [comment]
Currently, there are no ARM version binary generated but we have an action item related to this issue which we will add this in the near future.

**Comment by gauravpurohit06** [comment]
Thanks you @nghialv  for filing the issue.  Starting from version `1.5.6` we will also be publishing the arm64 binary image and you can download the same using following commands: 
`
VERSION=1.5.6
wget https://storage.googleapis.com/cloud-spanner-emulator/releases/${VERSION}/cloud-spanner-emulator_linux_arm64-${VERSION}.tar.gz
tar xvf cloud-spanner-emulator_linux_arm64-${VERSION}.tar.gz

`

**Comment by nghialv** [comment]
@gauravpurohit06 Nice to hear about that! Thank you for your support.

**Comment by iurisilvio** [comment]
Looks like latest ARM release was 1.5.10. Something changed?

**Comment by jduan-highnote** [comment]
Looks like it. I see this for 1.5.28 on my mac:

<img width="1417" alt="Image" src="https://github.com/user-attachments/assets/ed70ef22-38d3-4244-925a-4ace063cf21d" />
